# Generated by Django 5.2.5 on 2025-09-02 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Disciplines", "0002_initial"),
        ("Lessons", "0002_initial"),
        ("Payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="priceconfiguration",
            name="discipline",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_config",
                to="Disciplines.discipline",
                verbose_name="Дисциплина",
            ),
        ),
        migrations.AddField(
            model_name="priceconfiguration",
            name="lesson",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_config",
                to="Lessons.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AddField(
            model_name="purchasedcontent",
            name="discipline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_by",
                to="Disciplines.discipline",
                verbose_name="Купленная дисциплина",
            ),
        ),
        migrations.AddField(
            model_name="purchasedcontent",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_by",
                to="Lessons.lesson",
                verbose_name="Купленный урок",
            ),
        ),
        migrations.AddField(
            model_name="purchasedcontent",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_content",
                to="Payments.payment",
                verbose_name="Связанный платеж",
            ),
        ),
        migrations.AddField(
            model_name="purchasedcontent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_content",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchasedcontent",
            unique_together={("user", "discipline"), ("user", "lesson")},
        ),
    ]
