# Generated by Django 5.2.5 on 2025-08-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
