# Generated by Django 5.2.5 on 2025-08-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payments", "0003_payment_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата обновления"
            ),
        ),
    ]
