# Generated by Django 5.2.5 on 2025-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Административный ключ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата истечения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email, на который был отправлен ключ (для удобства)",
                        max_length=254,
                        null=True,
                        verbose_name="Email для ключа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Административный ключ",
                "verbose_name_plural": "Административные ключи",
            },
        ),
    ]
