# Generated by Django 5.2.5 on 2025-08-24 18:39

import Users.models
import django.utils.timezone
import utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Студент"),
                            ("teacher", "Преподаватель"),
                            ("admin", "Администратор"),
                            ("moderator", "Модератор"),
                        ],
                        default="student",
                        max_length=10,
                        verbose_name="Роль пользователя",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите свой email",
                        max_length=254,
                        unique=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите фамилию",
                        max_length=150,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите имя",
                        max_length=150,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="Введите отчество",
                        max_length=150,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату рождения",
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="В формате +79991234567",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите аватарку",
                        null=True,
                        upload_to="avatars/",
                        validators=[utils.image_validators.validate_image_file],
                        verbose_name="Аватарка",
                    ),
                ),
                (
                    "is_admin_key_required",
                    models.BooleanField(
                        default=False,
                        help_text="Если True, пользователь должен будет предоставить уникальный админ-ключ для входа/регистрации с ролью администратора/модератора.",
                        verbose_name="Требуется админ-ключ для входа",
                    ),
                ),
                (
                    "has_logged_in_with_key",
                    models.BooleanField(
                        default=False,
                        help_text="Показывает, совершал ли пользователь вход с использованием админ-ключа.",
                        verbose_name="Входил с админ-ключом",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Группы, к которым принадлежит пользователь. Пользователь получит все разрешения, предоставленные каждой из его групп.",
                        related_name="user_groups",
                        to="auth.group",
                        verbose_name="Группы",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Специфические разрешения для этого пользователя.",
                        related_name="user_user_permissions",
                        to="auth.permission",
                        verbose_name="Права пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
            managers=[
                ("objects", Users.models.CustomUserManager()),
            ],
        ),
    ]
