# Generated by Django 5.2.5 on 2025-09-02 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1 курс"),
                            (2, "2 курс"),
                            (3, "3 курс"),
                            (4, "4 курс"),
                            (5, "5 курс"),
                            (6, "6 курс"),
                        ],
                        help_text="Выберите курс обучения",
                        null=True,
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
            },
        ),
    ]
