# Generated by Django 5.2.5 on 2025-08-24 18:39

import utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="previews/",
                        validators=[utils.image_validators.validate_image_file],
                        verbose_name="Превью",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Порядок дисциплины в общем каталоге (1, 2, 3...)",
                        verbose_name="Порядок отображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Например: 'Глава 1. Основы алгебры', 'Модуль 2. Уравнения'",
                        max_length=200,
                        verbose_name="Название раздела",
                    ),
                ),
                (
                    "section_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Порядок раздела в дисциплине (1, 2, 3...)",
                        verbose_name="Номер раздела",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел дисциплины",
                "verbose_name_plural": "Разделы дисциплин",
                "ordering": ["section_order"],
            },
        ),
    ]
