# Generated by Django 5.2.5 on 2025-09-02 15:09

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings

# Use TrigramExtension operation instead of raw SQL for pg_trgm
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Disciplines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Ensure pg_trgm extension exists before creating GIN index that depends on it.
        TrigramExtension(),
        migrations.AddField(
            model_name="discipline",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="discipline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="Disciplines.discipline",
                verbose_name="Дисциплина",
            ),
        ),
        migrations.AddIndex(
            model_name="discipline",
            index=models.Index(
                django.db.models.functions.text.Lower("title"),
                name="discipline_title_lower_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discipline",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="discipline_title_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("discipline", "section_order")},
        ),
    ]
