# Generated by Django 5.2.5 on 2025-08-24 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Disciplines", "0002_initial"),
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disciplines",
                    models.ManyToManyField(
                        help_text="Дисциплины, которые преподает этот учитель.",
                        to="Disciplines.discipline",
                        verbose_name="Предметы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
            },
        ),
    ]
