# Generated by Django 5.2.5 on 2025-09-02 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Disciplines", "0002_initial"),
        ("Exercises", "0001_initial"),
        ("Lessons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, сделавший выбор.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                help_text="Вопрос, на который дан ответ.",
                on_delete=django.db.models.deletion.CASCADE,
                to="Exercises.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                help_text="Вопрос, к которому относится ответ.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="Exercises.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AddField(
            model_name="questionhint",
            name="question",
            field=models.OneToOneField(
                help_text="Вопрос, к которому относится подсказка.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hint",
                to="Exercises.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, проходящий тест.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="quiz_attempt",
            field=models.ForeignKey(
                help_text="Попытка прохождения теста, к которой относится этот выбор.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="Exercises.quizattempt",
                verbose_name="Попытка теста",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="discipline",
            field=models.ForeignKey(
                help_text="Дисциплина, к которой относится тест.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="Disciplines.discipline",
                verbose_name="Предмет",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Урок, к которому относится тест (необязательно).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="Lessons.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, создавший тест.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец теста",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Раздел дисциплины, к которому относится тест (необязательно).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="Disciplines.section",
                verbose_name="Раздел",
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="quiz",
            field=models.ForeignKey(
                help_text="Тест, который проходит пользователь.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="Exercises.test",
                verbose_name="Тест",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                help_text="Тест, к которому относится вопрос.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="Exercises.test",
                verbose_name="Тест",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="choice",
            unique_together={("user", "question", "quiz_attempt", "answer")},
        ),
    ]
