# Generated by Django 5.2.5 on 2025-08-24 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Введите текст ответа. Максимальная длина - 255 символов.",
                        max_length=255,
                        verbose_name="Текст ответа",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Указывает, является ли этот ответ правильным.",
                        verbose_name="Правильный ответ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст вопроса.", verbose_name="Текст вопроса"
                    ),
                ),
                (
                    "question_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Порядковый номер вопроса в тесте (1, 2, 3...)",
                        verbose_name="Номер вопроса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["question_order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionHint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст подсказки, которая будет показана после ошибки.",
                        verbose_name="Текст подсказки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подсказка к вопросу",
                "verbose_name_plural": "Подсказки к вопросам",
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время начала попытки.",
                        verbose_name="Время начала",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время окончания попытки.",
                        null=True,
                        verbose_name="Время окончания",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0,
                        help_text="Количество набранных баллов за тест.",
                        verbose_name="Набранные баллы",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Флаг, указывающий, завершена ли попытка.",
                        verbose_name="Попытка завершена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка прохождения теста",
                "verbose_name_plural": "Попытки прохождения тестов",
            },
        ),
        migrations.CreateModel(
            name="QuizCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например, 'Тест по главе 3'",
                        max_length=100,
                        unique=True,
                        verbose_name="Название категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория теста",
                "verbose_name_plural": "Категории тестов",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название теста. Максимальная длина - 255 символов.",
                        max_length=255,
                        verbose_name="Название теста",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание теста.",
                        null=True,
                        verbose_name="Описание теста",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания теста.",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления теста.",
                        verbose_name="Дата обновления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время, когда был сделан выбор.",
                        verbose_name="Время выбора",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        help_text="Выбранный пользователем вариант ответа.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Tests.answer",
                        verbose_name="Выбранный ответ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выбор ответа",
                "verbose_name_plural": "Выборы ответов",
            },
        ),
    ]
