# Generated by Django 5.2.5 on 2025-08-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_multiple",
            field=models.BooleanField(
                default=False,
                help_text="Если выбрано, пользователь может выбрать несколько вариантов ответа.",
                verbose_name="Множественный выбор",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Порядковый номер вопроса в тесте (1, 2, 3...)",
                verbose_name="Номер вопроса",
            ),
        ),
    ]
