# Generated by Django 5.2.5 on 2025-08-24 18:39

import django.db.models.deletion
import utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Disciplines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Урок пройден"),
                ),
                (
                    "current_time",
                    models.FloatField(
                        default=0.0, verbose_name="Текущее время воспроизведения (сек)"
                    ),
                ),
                (
                    "watched_duration",
                    models.IntegerField(default=0, verbose_name="Просмотрено секунд"),
                ),
                (
                    "last_watched_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последний просмотр"
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс урока пользователя",
                "verbose_name_plural": "Прогресс уроков пользователей",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название урока"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Описание урока",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="lesson_previews/",
                        validators=[utils.image_validators.validate_image_file],
                        verbose_name="Превью урока",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="URL видео"),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="lesson_videos/",
                        verbose_name="Видео файл",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "lesson_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Порядковый номер урока в разделе или дисциплине (1, 2, 3...)",
                        verbose_name="Номер урока",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="Disciplines.discipline",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["discipline", "section", "lesson_order"],
            },
        ),
    ]
