# Generated by Django 5.2.5 on 2025-09-02 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Disciplines", "0002_initial"),
        ("Lessons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец урока",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="К какому разделу дисциплины относится урок (например: 'Глава 1. Введение', 'Тема: Дроби'). Если не указан - урок будет в общем списке дисциплины. Вы можете создать разделы в разделе 'Предметы'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="Disciplines.section",
                verbose_name="Раздел дисциплины",
            ),
        ),
        migrations.AddField(
            model_name="userlessonprogress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progresses",
                to="Lessons.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AddField(
            model_name="userlessonprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userlessonprogress",
            unique_together={("user", "lesson")},
        ),
    ]
