# Generated by Django 5.2.5 on 2025-08-24 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Disciplines", "0002_initial"),
        ("Lessons", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="К какому разделу дисциплины относится урок (например: 'Глава 1. Введение', 'Тема: Дроби'). Если не указан - урок будет в общем списке дисциплины. Вы можете создать разделы для дисциплины в административной панели дисциплины.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="Disciplines.section",
                verbose_name="Раздел дисциплины",
            ),
        ),
    ]
